### ISSUE TITLE
Production deploy to local IIS and browsing to URL only produce hourglass

### ISSUE THREAD

**Issue by andyfensham** [NetFrameworkTemplates/vuetify-nuxt-netfx#1]
Cloned the repo, run successfully locally.  When publishing to IIS, I can browse to localhost/MyApp/metadata and execute the services, but the front end only shows hourglass. Tried to go to localhost/MyApp/index and localhost/MyApp/posts/1 etc but not working

**Comment by mythz** [comment]
You wont be able to run the generated website from a virtual directory as the Nuxt build generates absolute paths:

```html
<link rel="preload" href="/_nuxt/a9ffa03f7b76fcee36f7.js" as="script">
```

Expecting the Web App to be [hosted at an virtual domain](https://docs.servicestack.net/netcore-deploy-rsync), e.g. sub.domain.org instead of a Virtual Directory like `/VirtualPath`.

It would require an additional post script to rewrite all absolute references to include your VirtualPath.
